// NOTE: this server is purely a dev-mode server. In production, the
// server/index.js server also serves the API routes.

// Configure process.env with .env.* files
require('./env').configureEnv();

const express = require('express');
const compression = require('compression');
const cookieParser = require('cookie-parser');
const bodyParser = require('body-parser');
const cors = require('cors');
const apiRouter = require('./apiRouter');
const wellKnownRouter = require('./wellKnownRouter');
const webmanifestResourceRoute = require('./resources/webmanifest');
const robotsTxtRoute = require('./resources/robotsTxt');
const sitemapResourceRoute = require('./resources/sitemap');
const listingsFeedRoute = require('./resources/listingsFeed');

const radix = 10;
const PORT = parseInt(process.env.REACT_APP_DEV_API_SERVER_PORT, radix);
const app = express();

// NOTE: CORS is only needed in this dev API server because it's
// running in a different port than the main app.
// FAIRWAY: also the same frontend opened from another machine on the local
// network (http://192.168.x.x:3000), so the site can be shown on a second
// computer while this one runs it. Private-range addresses on the frontend's
// port only — this is the dev server, and nothing outside the LAN matches.
const rootUrl = process.env.REACT_APP_MARKETPLACE_ROOT_URL;
const frontendPort = (() => {
  try {
    return new URL(rootUrl).port;
  } catch (e) {
    return '3000';
  }
})();
const LAN_ORIGIN = new RegExp(
  `^http://(192\\.168\\.\\d+\\.\\d+|10\\.\\d+\\.\\d+\\.\\d+|172\\.(1[6-9]|2\\d|3[01])\\.\\d+\\.\\d+):${frontendPort}$`
);

app.use(
  cors({
    origin: [rootUrl, LAN_ORIGIN],
    credentials: true,
  })
);
app.use(cookieParser());
app.use('/.well-known', wellKnownRouter);
app.use('/api', apiRouter);

// Generate web app manifest
// When developing with "yarn run dev",
// you can reach the manifest from http://localhost:3500/site.webmanifest
// The corresponding <link> element is set in src/components/Page/Page.js
app.get('/site.webmanifest', webmanifestResourceRoute);

// robots.txt and sitemap-* fetches should return similarly compressed data as server/index.js
app.use(compression());

// robots.txt is generated by resources/robotsTxt.js
// It creates the sitemap URL with the correct marketplace URL
app.get('/robots.txt', robotsTxtRoute);

// Handle different sitemap-* resources. E.g. /sitemap-index.xml
app.get('/sitemap-:resource', sitemapResourceRoute);

// FAIRWAY: RSS feed of the newest listings (server/index.js serves it in production)
app.get('/feed/nyeste-annoncer.xml', listingsFeedRoute);

app.listen(PORT, () => {
  // eslint-disable-next-line no-console
  console.log(`API server listening on ${PORT}`);
});
